# Generated by Django 4.1.6 on 2023-03-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donaterequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaterequestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
