# Generated by Django 4.1.6 on 2023-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donaterequestmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaterequestmodel',
            name='donor',
            field=models.PositiveIntegerField(),
        ),
    ]
