# Generated by Django 4.1.6 on 2023-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_donaterequestmodel_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donaterequestmodel',
            old_name='donor',
            new_name='requested_donor_id',
        ),
    ]
