# Generated by Django 4.1.6 on 2023-03-09 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patientMoel',
            new_name='patientModel',
        ),
    ]
