# Generated by Django 4.1.6 on 2023-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_patientmoel_patientmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
