# Generated by Django 4.1.6 on 2023-03-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientmodel_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='is_patient',
        ),
    ]
