# Generated by Django 4.1.6 on 2023-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patientmodel_is_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='age',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
