# Generated by Django 4.1.6 on 2023-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patientmodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='bloodtype',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=10),
        ),
    ]
