# Generated by Django 4.1.6 on 2023-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default=None, max_length=10)),
                ('unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blood',
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='bloodtype',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='reason',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='requested_donor_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='requested_patient_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Denied', 'Denied')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='unit',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
