# Generated by Django 4.1.6 on 2023-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0002_bloodmodel_delete_blood_bloodrequestmodel_bloodtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Denied', 'Denied')], default='Pending', max_length=255),
        ),
    ]
