# Generated by Django 4.1.6 on 2023-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0003_alter_bloodrequestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequestmodel',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
