# Generated by Django 4.1.6 on 2023-03-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0004_bloodrequestmodel_is_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestmodel',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='bloodrequestmodel',
            name='is_patient',
        ),
    ]
